// @vitest-environment jsdom
import { afterEach, beforeEach, describe, it, expect, vi } from 'vitest';
import { render, screen, fireEvent, cleanup, waitFor } from '@testing-library/react';
import App from './App';
import { blankProject, blankSegment, blankWorkspace } from './model';
import { loadWorkspace, saveWorkspace } from './storage';
vi.mock('virtual:pwa-register/react', () => ({ useRegisterSW: () => ({ needRefresh: [false], offlineReady: [false], updateServiceWorker: vi.fn() }) }));
vi.mock('./storage', async (original) => ({ ...await original<typeof import('./storage')>(), loadWorkspace: vi.fn(), saveWorkspace: vi.fn(async () => 1) }));
beforeEach(() => { vi.mocked(loadWorkspace).mockResolvedValue({ workspace: blankWorkspace(), revision: 0, migrated: false }); vi.mocked(saveWorkspace).mockClear(); });
afterEach(cleanup);
describe('편집 흐름', () => {
    it('새 작품을 만들고 다른 작품으로 전환해도 기준이 섞이지 않는다', async () => { render(<App />); await screen.findByLabelText('새 작품 이름'); fireEvent.change(screen.getByLabelText('새 작품 이름'), { target: { value: '테스트 작품 하나' } }); fireEvent.click(screen.getByRole('button', { name: '새 작품 만들기' })); fireEvent.click(screen.getByRole('button', { name: '작품 기준집' })); fireEvent.change(screen.getByLabelText('요약'), { target: { value: '첫 작품 전용 기준' } }); fireEvent.click(screen.getByRole('button', { name: '작품 서재' })); fireEvent.change(screen.getByLabelText('새 작품 이름'), { target: { value: '테스트 작품 둘' } }); fireEvent.click(screen.getByRole('button', { name: '새 작품 만들기' })); fireEvent.click(screen.getByRole('button', { name: '작품 기준집' })); expect((screen.getByLabelText('요약') as HTMLTextAreaElement).value).toBe(''); const select = screen.getByLabelText('현재 작품') as HTMLSelectElement; const first = Array.from(select.options).find(o => o.text === '테스트 작품 하나')!; fireEvent.change(select, { target: { value: first.value } }); expect((screen.getByLabelText('요약') as HTMLTextAreaElement).value).toBe('첫 작품 전용 기준'); await waitFor(() => expect(saveWorkspace).toHaveBeenCalled()); });
    it('확장본의 문단을 후보로 저장해도 최종본은 비어 있다', async () => { const p = blankProject('테스트 작품'), s = blankSegment('테스트 장면'); s.original = '원본 문단'; s.expanded = '확장 문단'; p.segments = [s]; p.selectedId = s.id; vi.mocked(loadWorkspace).mockResolvedValue({ workspace: { schemaVersion: 2, projects: [p], activeId: p.id }, revision: 0, migrated: false }); render(<App />); await screen.findByLabelText('새 작품 이름'); fireEvent.click(screen.getByRole('button', { name: '확장본·후보' })); fireEvent.click(screen.getByLabelText('문단 1 후보 선택')); fireEvent.click(screen.getByRole('button', { name: '체크한 문단 후보 보관 (1)' })); expect(screen.getByRole('heading', { name: '내가 고른 후보 · 1' })).toBeTruthy(); expect((screen.getByLabelText('내가 작성하는 최종본') as HTMLTextAreaElement).value).toBe(''); await waitFor(() => expect(saveWorkspace).toHaveBeenCalled()); const saved = vi.mocked(saveWorkspace).mock.calls.at(-1)![0]; expect(saved.projects[0].segments[0].candidates[0].text).toBe('확장 문단'); expect(saved.projects[0].segments[0].final).toBe(''); });
    it('원고를 넣고 제목 분리 미리보기를 확인해야 목차가 늘어난다', async () => { const p = blankProject('테스트 작품'); vi.mocked(loadWorkspace).mockResolvedValue({ workspace: { schemaVersion: 2, projects: [p], activeId: p.id }, revision: 0, migrated: false }); render(<App />); await screen.findByLabelText('새 작품 이름'); fireEvent.click(screen.getByRole('button', { name: '원고 서재' })); fireEvent.change(screen.getByLabelText('붙여넣을 긴 원고'), { target: { value: '# 첫 제목\n첫 본문\n# 둘째 제목\n둘째 본문' } }); fireEvent.change(screen.getByLabelText('분리 방식'), { target: { value: 'heading' } }); fireEvent.click(screen.getByRole('button', { name: '분리 미리보기' })); expect(screen.getByLabelText('분리 원고 2 제목')).toBeTruthy(); fireEvent.click(screen.getByRole('button', { name: '확인한 원고 저장' })); expect((screen.getByLabelText('원본 원고') as HTMLTextAreaElement).value).toBe('# 첫 제목\n첫 본문\n'); expect(screen.getByText('가져온 원문 보관함 (1)')).toBeTruthy(); });
    it('저장 실패 시 현재 작업을 백업할 수 있는 경고를 유지한다', async () => { vi.mocked(saveWorkspace).mockRejectedValueOnce(new Error('저장 실패 테스트')); render(<App />); await screen.findByLabelText('새 작품 이름'); expect(await screen.findByRole('alert')).toBeTruthy(); expect(screen.getByRole('button', { name: '현재 작업 전체 백업' })).toBeTruthy(); });
});
