// @vitest-environment jsdom
import { describe, it, expect, beforeEach } from 'vitest';
import 'fake-indexeddb/auto';
import { blankWorkspace, blankProject, blankSegment, duplicateProject, splitText, importSegments, storeCandidates, exportManuscript, snapshot, orderedSegments, type Card } from './model';
import { validateWorkspace, validateProject, criteriaOnly, parseBackup, applyBackup, migrateLegacy, loadWorkspace, saveWorkspace } from './storage';
import { inspect, searchContext, referenceScenes, contextFresh, contextPackage, buildPrompt } from './engine';
const make = () => { const p = blankProject('테스트 작품'); const s = blankSegment('테스트 장면'); p.segments = [s]; p.selectedId = s.id; return p; };
const card = (title: string, related = ''): Card => ({ id: crypto.randomUUID(), type: '인물', title, related, aliases: '', keywords: '', body: '테스트 카드 본문', tone: '', avoid: '' });
describe('작품과 원고 보존', () => {
    it('빈 작품은 원고와 설정을 미리 넣지 않는다', () => { const p = blankProject('새 작품'); expect(p.segments).toEqual([]); expect(p.cards).toEqual([]); expect(Object.values(p.criteria).every(v => v === '')).toBe(true); expect(blankWorkspace().projects).toEqual([]); });
    it('작품 복제는 하위 ID를 새로 만들고 선택 맥락을 비운다', () => { const p = make(); p.segments[0].kind = '권'; p.segments.push(blankSegment('하위 장면', '장면', p.selectedId)); p.selectedId = p.segments[1].id; p.cards = [card('테스트 인물')]; p.selectedCards = [p.cards[0].id]; const c = duplicateProject(p); expect(c.id).not.toBe(p.id); expect(c.segments[1].parentId).toBe(c.segments[0].id); expect(c.selectedId).toBe(c.segments[1].id); expect(c.selectedCards).toEqual([]); c.segments[0].original = '변경'; expect(p.segments[0].original).toBe(''); expect(validateProject(c)).toBeTruthy(); });
    it.each(['whole', 'heading', 'separator'] as const)('%s 분리는 모든 문자와 줄바꿈을 보존한다', mode => { const text = '앞머리\r\n# 첫 제목\r\n본문\r\n\r\n***\r\n뒤쪽\n# 둘째 제목\n끝\n'; expect(splitText(text, '원고', mode).map(p => p.text).join('')).toBe(text); });
    it('미리보기 후 원고가 바뀌면 오래된 미리보기를 저장하지 않는다', () => { const p = make(); p.importDraft.text = '# 제목\n본문'; const parts = splitText(p.importDraft.text, '', 'heading'); p.importDraft.text += '추가'; expect(() => importSegments(p, parts)).toThrow(); });
    it('분리 저장은 원문 보관과 새 원고를 함께 만든다', () => { const p = make(); p.importDraft.text = '# 제목\n본문\n# 다음\n뒤'; const n = importSegments(p, splitText(p.importDraft.text, '', 'heading')); expect(n.imports[0].text).toBe(p.importDraft.text); expect(n.segments.slice(1).map(s => s.original).join('')).toBe(p.importDraft.text); expect(n.importDraft.text).toBe(''); expect(validateProject(n)).toBeTruthy(); });
    it('잘못된 상위 목차 아래로 가져올 수 없다', () => { const p = make(); p.importDraft = { title: '', text: '본문', kind: '권', parentId: p.selectedId, mode: 'whole' }; expect(() => importSegments(p, [{ title: '제목', text: '본문' }])).toThrow(); });
    it('후보 저장은 원본과 최종본을 변경하지 않는다', () => { const s = blankSegment(); s.original = '원본'; s.final = '직접 작성한 최종본'; s.expanded = '첫 문단\n\n둘째 문단'; s.checked = [1]; const n = storeCandidates(s); expect(n.candidates.map(c => c.text)).toEqual(['둘째 문단']); expect(n.original).toBe('원본'); expect(n.final).toBe('직접 작성한 최종본'); expect(s.candidates).toEqual([]); });
    it('같은 문단을 반복 저장하지 않는다', () => { let s = blankSegment(); s.expanded = '문단'; s.checked = [0]; s = storeCandidates(s); s.checked = [0]; expect(storeCandidates(s).candidates).toHaveLength(1); });
    it('빈 최종본 내보내기가 원본을 대신 합치지 않는다', () => { const p = make(); p.segments[0].original = '원본만의 문자열'; expect(exportManuscript(p)).not.toContain('원본만의 문자열'); expect(exportManuscript(p, '', 'original')).toContain('원본만의 문자열'); });
    it('권 단위 내보내기는 그 권의 하위 원고만 포함한다', () => { const p = make(); p.segments[0].kind = '권'; const a = blankSegment('안쪽', '장면', p.selectedId), b = blankSegment('다른 권', '권'); a.final = '포함 본문'; b.final = '제외 본문'; p.segments.push(a, b); expect(orderedSegments(p).map(s => s.id)).toEqual([p.selectedId, a.id, b.id]); const out = exportManuscript(p, p.selectedId); expect(out).toContain('포함 본문'); expect(out).not.toContain('제외 본문'); });
    it('보관 버전은 세 원고를 각각 복사한다', () => { const s = blankSegment(); s.original = '원본'; s.expanded = '확장'; s.final = '최종'; expect(snapshot(s, '저장')).toMatchObject({ original: '원본', expanded: '확장', final: '최종' }); });
});
describe('기준과 맥락의 작품 격리', () => {
    it('현재 작품의 카드만 검색한다', () => { const a = make(), b = make(); a.cards = [card('테스트 인물')]; b.cards = [card('다른 인물')]; a.segments[0].original = '테스트 인물과 다른 인물'; expect(searchContext(a).map(h => h.card.title)).toEqual(['테스트 인물']); expect(searchContext(b)).toEqual([]); });
    it('같은 키워드를 반복해도 점수가 부풀지 않는다', () => { const p = make(); p.cards = [card('테스트 인물')]; expect(searchContext(p, '테스트 인물')[0].score).toBe(searchContext(p, '테스트 인물 '.repeat(30))[0].score); });
    it('관계 연결은 직접 일치 카드에서 한 단계까지만 찾는다', () => { const p = make(); p.cards = [card('첫 카드', '중간 카드'), card('중간 카드', '마지막 카드'), card('마지막 카드')]; expect(searchContext(p, '첫 카드').map(h => h.card.title)).toEqual(['첫 카드', '중간 카드']); });
    it('수정 전 맥락은 패키지에 넣지 않는다', () => { const p = make(); p.segments[0].original = '첫 카드'; p.cards = [card('첫 카드')]; p.contextQuery = '첫 카드'; p.contextSegmentId = p.selectedId; p.selectedCards = [p.cards[0].id]; expect(contextPackage(p)).toContain('첫 카드'); p.segments[0].original = '변경된 원고'; expect(contextFresh(p)).toBe(false); expect(() => contextPackage(p)).toThrow(); expect(buildPrompt(p)).not.toContain('[인물] 첫 카드'); });
    it('다른 장면으로 바꾸면 같은 본문이어도 맥락을 다시 선택한다', () => { const p = make(); p.segments[0].original = '내용'; p.contextQuery = '내용'; p.contextSegmentId = p.selectedId; const s = blankSegment(); s.original = '내용'; p.segments.push(s); p.selectedId = s.id; expect(contextFresh(p)).toBe(false); });
    it('참고 원고와 프롬프트에 다른 작품은 포함되지 않는다', () => { const p = make(); p.cards = [card('테스트 인물')]; p.segments[0].original = '테스트 인물'; const s = blankSegment('이전 장면'); s.original = '테스트 인물의 이전 기록'; p.segments.push(s); p.contextQuery = p.segments[0].original; p.contextSegmentId = p.selectedId; p.referenceIds = [s.id]; expect(referenceScenes(p)).toHaveLength(1); expect(buildPrompt(p)).toContain(s.original); });
    it('설정 규칙의 일치 근거와 행 번호를 표시한다', () => { const p = make(); p.banned = '금지표현'; const out = inspect(p, '첫 줄\n금지표현'); expect(out[0]).toMatchObject({ level: '필수 수정', line: 2 }); expect(out[0].quote).toContain('금지표현'); });
    it('규칙 범위가 없으면 무관한 원고에 적용하지 않는다', () => { const p = make(); p.rules = [{ id: 'rule', term: '문구', message: '이유', scope: '범위명', level: '확인 필요' }]; expect(inspect(p, '문구').some(f => f.title.startsWith('작품 규칙'))).toBe(false); expect(inspect(p, '범위명 문구').some(f => f.title.startsWith('작품 규칙'))).toBe(true); });
    it('겹치는 반복 표현은 한 번만 센다', () => { const p = make(); p.repeat = '긴 표현 / 표현'; p.threshold = 3; expect(inspect(p, '긴 표현 긴 표현').some(f => f.title.startsWith('반복 표현'))).toBe(false); });
    it('확장본 검토 프롬프트는 원본·확장·후보를 구분한다', () => { const p = make(); p.promptKind = 'AI 확장본 취사선택'; p.segments[0].original = '원본 내용'; p.segments[0].expanded = '확장 내용'; const out = buildPrompt(p); expect(out).toContain('<원본>\n원본 내용'); expect(out).toContain('<AI_확장본>\n확장 내용'); expect(out).toContain('자동 윤문 금지'); expect(out).toContain('전체 재작성 금지'); });
});
it('등록하지 않은 반복 어절도 찾아준다',()=>{const p=make();expect(inspect(p,'테스트반복 테스트반복 테스트반복').some(f=>f.title==='반복 어절: 테스트반복')).toBe(true);});
describe('백업과 저장 안전성', () => {
    beforeEach(async () => { localStorage.clear(); await new Promise<void>((resolve, reject) => { const r = indexedDB.deleteDatabase('writing-studio-personal'); r.onsuccess = () => resolve(); r.onerror = () => reject(r.error); }); });
    it('JSON 전체 백업이 모든 원고와 후보를 보존한다', () => { const p = make(); p.segments[0].expanded = '후보'; p.segments[0].checked = [0]; p.segments[0] = storeCandidates(p.segments[0]); const w = { schemaVersion: 2 as const, projects: [p], activeId: p.id }; const b = parseBackup(JSON.stringify({ kind: 'workspace', workspace: w })); expect(applyBackup(blankWorkspace(), b)).toEqual(w); });
    it('작품 복원은 같은 ID를 덮어쓰지 않고 새 작품으로 추가한다', () => { const p = make(), w = { schemaVersion: 2 as const, projects: [p], activeId: p.id }; const restored = applyBackup(w, { kind: 'project', project: p }); expect(restored.projects).toHaveLength(2); expect(new Set(restored.projects.map(p => p.id)).size).toBe(2); expect(restored.projects[0]).toEqual(p); });
    it('기준집 백업에는 원고와 가져오기 초안이 없다', () => { const p = make(); p.segments[0].original = '비공개 원고'; p.importDraft.text = '비공개 초안'; p.criteria['요약'] = '기준 요약'; const c = criteriaOnly(p); expect(JSON.stringify(c)).not.toContain('비공개'); expect(c.criteria['요약']).toBe('기준 요약'); expect(validateProject(c)).toBeTruthy(); });
    it('기준집 복원은 현재 작품의 원고를 유지한다', () => { const p = make(), other = make(); p.segments[0].original = '현재 원고'; other.criteria['요약'] = '새 기준'; const w = applyBackup({ schemaVersion: 2, projects: [p], activeId: p.id }, { kind: 'criteria', project: other }); expect(w.projects[0].segments[0].original).toBe('현재 원고'); expect(w.projects[0].criteria['요약']).toBe('새 기준'); });
    it.each(['parent', 'duplicate', 'status', 'candidate', 'selected', 'draft'])('잘못된 %s 백업을 거부한다', kind => { const p = make(); if (kind === 'parent')
        p.segments[0].parentId = p.selectedId; if (kind === 'duplicate')
        p.segments.push(structuredClone(p.segments[0])); if (kind === 'status')
        (p.segments[0] as any).status = 'unknown'; if (kind === 'candidate')
        (p.segments[0] as any).candidates = [{ text: 'bad' }]; if (kind === 'selected')
        p.selectedId = 'missing'; if (kind === 'draft')
        p.importDraft.parentId = 'missing'; expect(() => validateProject(p)).toThrow(); });
    it('서재의 중복 작품 ID를 거부한다', () => { const p = make(); expect(() => validateWorkspace({ schemaVersion: 2, projects: [p, p], activeId: p.id })).toThrow(); });
    it('이전 저장 형식은 실행 시 데이터만 이전하고 원본 키를 남긴다', async () => { const raw = JSON.stringify({ title: '이전 작품', manuscript: '이전 본문', settings: '입력한 기준', rules: '표현=>이유=>필수 수정' }); localStorage.setItem('writing-studio-v1', raw); const r = await loadWorkspace(); expect(r.migrated).toBe(true); expect(r.workspace.projects[0].segments[0].original).toBe('이전 본문'); expect(localStorage.getItem('writing-studio-v1')).toBe(raw); expect(validateWorkspace(migrateLegacy(raw))).toBeTruthy(); });
    it('손상된 이전 저장 형식을 빈 서재로 덮지 않는다', async () => { localStorage.setItem('writing-studio-v1', '{broken'); await expect(loadWorkspace()).rejects.toThrow(); });
    it('IndexedDB 저장 후 세 원고와 선택 상태를 복원한다', async () => { const p = make(); p.segments[0].original = '원본'; p.segments[0].expanded = '확장'; p.segments[0].final = '최종'; const w = { schemaVersion: 2 as const, projects: [p], activeId: p.id }; expect(await saveWorkspace(w, 0)).toBe(1); const r = await loadWorkspace(); expect(r.workspace).toEqual(w); expect(r.revision).toBe(1); });
    it('다른 탭의 오래된 저장이 최신 원고를 덮어쓰지 않는다', async () => { const w = blankWorkspace(); await saveWorkspace(w, 0); await expect(saveWorkspace(w, 0)).rejects.toThrow('다른 탭'); expect((await loadWorkspace()).revision).toBe(1); });
});
